services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - pgvector_network

networks:
  pgvector_network:
    external: true
